version: 2

models:
    - name: int_orders_enriched
      columns: 
        - name: order_id
          tests: 
             - unique
             - not_null
        - name: customer_id
          tests: 
            - not_null
        - name: store_id
          tests: 
            - not_null
        - name: canal
          tests: 
            - accepted_values: 
                values: ['marketplace', 'online', 'magasin']
        - name: statut_livraison
          tests: 
            - accepted_values:
                values: ['confirmée', 'expédiée', 'livrée', 'annulée', 'remboursée']
        - name: date_commande
        - name: date_expedition
        - name: date_livraison
        - name: nb_lignes
        - name: quantite_totale
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: montant_calcule_ht
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: tva
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: montant_calcule_ttc
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: marge_brute_ht
          tests: 
            - dbt_utils.expression_is_true:
                expression: "<= montant_calcule_ht"
                config: 
                    severity: warn
        - name: promotion_id
        - name: code_promo
        - name: remise_pct
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: delai_expedition_jours
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
                config: 
                    severity: warn
        - name: delai_livraison_jours
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
                config: 
                    severity: warn
        - name: is_online
          tests: 
            - accepted_values: 
                values: [true, false]
        - name: has_promotion
          tests: 
            - accepted_values: 
                values: [true, false]
        - name: is_returned 
          tests: 
            - accepted_values: 
                values: [true, false]
    - name: int_customers_enriched
      columns:
        - name: customer_id
          tests:
            - unique
            - not_null
        - name: nom
          tests:
            - not_null
        - name: prenom
          tests:
            - not_null
        - name: email
        - name: telephone
        - name: rue
        - name: ville
        - name: pays
          tests:
            - accepted_values: 
                values: ['France','Belgique', 'Suisse', 'Allemagne', 'Luxembourg']
        - name: date_inscription
        - name: date_naissance
        - name: newsletter
          tests: 
            - accepted_values: 
                values: [true, false]
        - name: segment
          tests:
            - accepted_values:
                values: ['Grand public', 'Professionnel', 'Club/Association', 'Sportif régulier']
        - name: rfm_score
        - name: segment_label
          tests:
            - accepted_values:
                values: ['Loyal', 'At Risk', 'Potential Loyalist', 'Hibernating', 'Champions', 'Cannot Lose Them']
        - name: total_achats_ht
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: nb_commandes
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: points_solde
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: niveau
          tests:
            - accepted_values:
                values: ['Bronze', 'Silver', 'Gold', 'Platinum']

    - name: int_product_current_price
      columns: 
        - name: product_id 
          tests: 
            - not_null
            - unique
        - name: valid_from 
        - name: is_current
          tests: 
            - accepted_values:
                values: [true, false]
        - name: motif
          tests: 
            - accepted_values: 
                values: ['promotion saisonnière','réajustement', 'soldes','lancement']
                config: 
                  severity: warn
        - name: categorie
          tests:
            - accepted_values:
                values: ['Accessoires', 'Chaussures', 'Vêtements techniques', 'Équipement', 'Autre']
        - name: product_name
        - name: prix_achat_ht
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: prix_vente_ht
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: marge_unitaire_ht
        - name: taux_marge_pct
          tests: 
            - dbt_utils.expression_is_true:
                expression: "<= 100"

    - name: int_loyalty_balance
      columns: 
        - name: loyalty_account_id
          tests: 
            - unique
            - not_null
        - name: customer_id
          tests: 
            - relationships:
                to: ref('stg_customers')
                field: customer_id
        - name: solde_declare
        - name: solde_recalcule
          tests: 
            - not_null
        - name: ecart_solde
          tests:
            - dbt_utils.expression_is_true:
                expression: "!= 0"
                config:
                  severity: warn
        - name: niveau
        - name: date_adhesion
        - name: nb_transactions
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: derniere_transaction

    - name: int_product_variants_stock
      columns: 
        - name: product_id
          tests: 
            - unique
            - not_null
        - name: stock_total
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: nb_variantes
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: nb_variantes_stock
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: has_stock
          tests: 
            - accepted_values:
                values: [true,false]
    - name: int_loyalty_transactions
      columns: 
        - name:  loyalty_account_id
          tests: 
            - unique
            - not_null
        - name: total_points_gagnes
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: total_points_depenses
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
        - name: total_points_expires
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">=0"
    