version: 2

models:
    - name: stg_orders
      columns: 
        - name: order_id
          tests:
            - unique
            - not_null
        - name: customer_id
          tests:
            - not_null
        - name: statut
          tests: 
            - accepted_values:
                values: ['confirmée', 'expédiée', 'livrée', 'annulée', 'remboursée']
        - name: montant_total_ht
          tests: 
            - not_null
    - name: stg_customers
      columns: 
        - name: customer_id
          tests: 
            - not_null
            - unique
        - name : email
          tests: 
            - not_null:
                config:
                    severity: warn  
        - name : pays
          tests: 
            - accepted_values:
                values: ['France','Belgique', 'Suisse', 'Allemagne', 'Luxembourg']
    - name: stg_products
      columns: 
        - name: product_id 
          tests: 
            - not_null
            - unique 
        - name: prix_vente_ht
          tests: 
            - not_null:
                config:
                  severity: warn
            - dbt_utils.expression_is_true:
                expression: ">= 0"
        - name: product_name
          tests: 
            - not_null
        - name: categorie
          tests:
            - accepted_values:
                values: ['Accessoires', 'Chaussures', 'Vêtements techniques', 'Equipements', 'Autre']
        - name: ean13
          tests: 
            - unique:
                config:
                  severity: warn