version: 2

models:
    - name: stg_orders
      columns: 
        - name: order_id
          tests:
            - unique
            - not_null
        - name: customer_id
          tests:
            - not_null
        - name: statut
          tests: 
            - accepted_values:
                values: ['confirmée', 'expédiée', 'livrée', 'annulée', 'remboursée']
        - name: montant_total_ht
          tests: 
            - not_null
    - name: stg_customers
      columns: 
        - name: customer_id
          tests: 
            - not_null
            - unique
        - name : email
          tests: 
            - not_null:
                config:
                    severity: warn  
        - name : pays
          tests: 
            - accepted_values:
                values: ['France','Belgique', 'Suisse', 'Allemagne', 'Luxembourg']
    - name: stg_products
      columns: 
        - name: product_id 
          tests: 
            - not_null
            - unique 
        - name: prix_vente_ht
          tests: 
            - not_null:
                config:
                  severity: warn
            - dbt_utils.expression_is_true:
                expression: ">= 0"
        - name: product_name
          tests: 
            - not_null
        - name: categorie
          tests:
            - accepted_values:
                values: ['Accessoires', 'Chaussures', 'Vêtements techniques', 'Equipements', 'Autre']
        - name: ean13
          tests: 
            - unique:
                config:
                  severity: warn
    - name: stg_products_variants
      columns: 
        - name: variant_id
          tests: 
            - not_null
            - unique
        - name: product_id
          tests: 
            - relationships:
                to: ref('stg_products')
                field: product_id
        - name: sku
          tests: 
            - unique:
                config:
                  severity: warn
            - not_null
    - name: stg_price_history
      columns: 
        - name: price_history_id
          tests: 
            - unique
            - not_null 
        - name: product_id
          tests: 
            - relationships: 
                to: ref('stg_products')
                field: product_id
        - name: prix_vente_ht 
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">= 0"
        - name: is_current
          tests: 
            - accepted_values:
                values: ['0','1']
        - name: motif
          tests: 
            - accepted_values: 
                values: ['promotion saisonnière','réajustement', 'soldes','lancement']
                config: 
                  severity: warn
    - name: stg_order_items
      columns: 
        - name: order_item_id
          tests: 
            - unique
            - not_null
        - name: order_id
          #tests: 
          #  - relationships:
          #      to: ref('stg_orders')
          #      field: order_id
        - name: product_id 
          tests: 
            - relationships:
                to: ref('stg_products')
                field: product_id
        - name: variant_id 
          tests: 
            - relationships:
                to: ref('stg_products_variants')
                field: variant_id
        - name: quantite
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">= 0"
        - name: prix_unitaire_ht
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">= 0"
        - name: remise_pct
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">= 0"
        - name: montant_ligne_ht
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">= 0"
        - name: promotion_id
          #tests: 
          #  - relationships: 
          #      to: ref('stg_promotions')
          #      field: promotion_id
          #      config:
          #        where: "promotion_id is not null" 
    - name: stg_stores
      columns: 
        - name: store_id
          tests: 
            - unique
            - not_null 
        - name: pays
          tests: 
            - accepted_values:
                values: ['France', 'Allemagne', 'Suisse', 'Belgique', 'Luxembourg']
        - name: type
          tests: 
            - accepted_values:
                values: ['magasin', 'e-commerce']
        - name: surface_m2
          tests: 
            - dbt_utils.expression_is_true:
                expression: ">0" 
                config: 
                  severity: warn
        - name: actif
          tests: 
            - accepted_values:
                values: [true, false]
    - name: stg_suppliers
      columns: 
        - name: supplier_id
          tests: 
            - unique
            - not_null
        - name: supplier_name
        - name: pays
        - name : delai_livraison_jours
          tests: 
            - not_null:
                config: 
                  severity: warn
            - dbt_utils.expression_is_true:
                expression: "> 0"
        - name: langue_contact
        - name: specialite
        - name: actif
        - name: siret_tva
          tests: 
            - unique: 
                config: 
                  severity: warn
            - not_null
    - name: stg_promotions
      columns: 
        - name: promotion_id
          tests: 
            - unique
            - not_null
        - name: code_promo
        - name: libelle
        - name: remise_pct
          tests: 
            - dbt_expectations.expect_column_values_to_be_between:
                min_value: 0 
                max_value: 100 
                row_condition: "promotion_id is not null" 
                strictly: false 
        - name: categories_cibles
        - name: date_debut
        - name: date_fin
        - name: active
          tests: 
            - accepted_values: 
                values: [true, false]
    - name: stg_returns
      columns: 
        - name: return_id
          tests: 
            - unique
            - not_null
        - name: order_id
          tests: 
            - relationships:
                to: ref('stg_orders')
                field: order_id
        - name: order_item_id
          tests: 
            - relationships:
                to: ref('stg_order_items')
                field: order_item_id
        - name: date_retour
        - name: motif 
          tests: 
            - accepted_values:
                values: ['Ne convient pas', 'Délai trop long', 'Défaut produit', 'Erreur commande', 'Taille incorrecte', 'Autre']
        - name: quantite_retournee
          tests: 
            - dbt_utils.expression_is_true:
                expression: "> 0"
        - name: statut
          tests: 
            - accepted_values:
                values: ['remboursé', 'reçu', 'refusé', 'en cours'] 
        - name: remboursement_ht
          tests: 
            - dbt_utils.expression_is_true:
                expression: "> 0"
                config: 
                  severity: warn

    - name: stg_addresses
      columns: 
        - name: address_id
          tests: 
            - unique
            - not_null
        - name: customer_id
          tests: 
            - relationships:
                to: ref('stg_customers')
                field: customer_id
        - name: type_address
          tests: 
            - accepted_values:
                values: ['principale', 'livraison', 'facturation']
        - name: rue 
          tests: 
            - not_null: 
                config: 
                  severity: warn
        - name: ville
          tests: 
            - not_null
        - name: code_postal
        - name: pays
          tests: 
            - accepted_values:
                values: ['France', 'Allemagne', 'Luxembourg', 'Suisse', 'Belgique']
        - name: active
          tests:
            - accepted_values:
                values: [true, false]
    - name: stg_loyalty_accounts
      columns: 
        - name: loyalty_account_id 
          tests: 
            - unique
            - not_null
        - name: customer_id 
          tests: 
            - relationships:
                to: ref('stg_customers')
                field: customer_id
        - name: points_solde
          tests:
            - dbt_utils.expression_is_true:
                expression: ">= 0"
        - name: niveau
          tests: 
            - accepted_values:
                values: ['Bronze', 'Silver', 'Gold', 'Platinum', 'Autre']
        - name: date_adhesion
        - name: active
          tests: 
            - accepted_values:
                values: [true, false]
    - name: stg_loyalty_transactions 
      columns: 
        - name: transaction_id
          tests: 
            - unique
            - not_null 
        - name: loyalty_account_id
          tests: 
            - relationships:
                to: ref('stg_loyalty_accounts')
                field: loyalty_account_id 
                config: 
                  severity: warn
        - name: customer_id 
          tests: 
            - relationships:
                to: ref('stg_customers')
                field: customer_id
        - name: type_transaction
          tests:
            - accepted_values:
                values: ['Crédité', 'Débité', 'Expiré', 'Bonus', 'Autre']
        - name: points
        - name: date_transaction
        - name: order_id
          tests: 
            - relationships: 
                to: ref('stg_orders')
                field: order_id
                config: 
                  where: "order_id is not null and order_id != ''"
        - name: description_transaction
    - name: stg_customers_segments
      columns: 
        - name: segment_id
          tests: 
            - unique
            - not_null
        - name: customer_id
          tests: 
            - relationships: 
                to: ref('stg_customers')
                field: customer_id
        - name: r_score
          tests:
            - dbt_expectations.expect_column_values_to_be_between:
                min_value: 1
                max_value: 5
                strictly: false
        - name: f_score
          tests:
            - dbt_expectations.expect_column_values_to_be_between:
                min_value: 1
                max_value: 5
                strictly: false
        - name: m_score
          tests:
            - dbt_expectations.expect_column_values_to_be_between:
                min_value: 1
                max_value: 5
                strictly: false
        - name: rfm_score
        - name: segment_label
          tests: 
            - accepted_values:
                values: ['At Risk','Potential Loyalist','Loyal','Cannot Lose Them', 'Hibernating', 'Champions']
        - name: date_calcul
        - name: total_achats_ht
          tests:
            - dbt_utils.expression_is_true:
                expression: ">= 0"
        - name: nb_commandes
          tests:
            - dbt_utils.expression_is_true:
                expression: ">= 0"