table _Mesures
	lineageTag: 1ff1866c-d7ac-439f-a4be-272e2aa26811

	measure 'CA HT' =
			
			SUM(fct_sales[ca_ligne_ht])
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: CA & Revenus
		lineageTag: b0a4aa43-ac81-41f4-8672-4ee8a626ae59

	measure 'CA TTC' =
			
			SUM(fct_sales[ca_ligne_ttc])
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: CA & Revenus
		lineageTag: ae106215-3887-4bdb-b5c9-9c60ed5d745d

	measure 'Marge HT' =
			
			SUM(fct_sales[marge_ligne_ht])
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: Marges
		lineageTag: db39ce4c-a5ff-44f6-a9cb-d4d7cb23b7ff

	measure 'Taux de Marge' =
			
			DIVIDE([Marge HT], [CA HT])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: Marges
		lineageTag: 28e38fea-4d16-4f9e-b31f-608ef9c41124

	measure 'Nb commandes' =
			
			DISTINCTCOUNT(fct_sales[order_id])
		formatString: 0
		displayFolder: Commandes
		lineageTag: 767ebd69-8443-4cbd-b0b9-b3567b06350a

	measure 'Quantité vendue' =
			
			SUM(fct_sales[quantite])
		formatString: 0
		displayFolder: Commandes
		lineageTag: 89675026-8372-44cd-83f6-fe3f9e52c473

	measure 'Panier moyen' =
			
			DIVIDE([CA HT],[Nb commandes])
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: Commandes
		lineageTag: 4a09f947-113d-425b-9ab4-fe76edafaeee

	measure 'Clients actifs' =
			
			DISTINCTCOUNT(fct_sales[customer_id])
		formatString: 0
		displayFolder: Clients
		lineageTag: 3ea42372-63e9-4f02-a0da-eb6028a4f515

	measure 'CA moy par client' =
			
			DIVIDE([CA HT],[Clients actifs])
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: CA & Revenus
		lineageTag: 1e77ca87-29dc-40e5-94f8-dd32e7b85b9d

	measure 'Commandes par Client' =
			
			DIVIDE([Nb commandes], [Clients actifs])
		formatString: 0.00
		displayFolder: Commandes
		lineageTag: 4d0fc852-3b4b-4a6f-a77d-800083702c61

	measure 'CA Promo HT' =
			
			CALCULATE(
			    [CA HT]
			    , NOT ISBLANK(fct_sales[promotion_id])
			    )
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: CA & Revenus
		lineageTag: 0e32c455-5c69-4920-aa46-7ff0998f7260

	measure 'Nb commandes promo' = ```
			
			CALCULATE( 
			    [Nb commandes]
			    , NOT ISBLANK(fct_sales[promotion_id])
			)
			```
		formatString: 0
		displayFolder: Promo
		lineageTag: b98abb92-99f1-40e3-97d9-72b8084a181e

	measure 'Part CA Promo' =
			
			DIVIDE([CA Promo HT], [CA HT])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: Promo
		lineageTag: adf9fdac-ee0d-4793-ab2d-82400143a727

	measure 'Taux commandes Promo' =
			
			DIVIDE([Nb commandes promo], [Nb commandes])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: Promo
		lineageTag: 9457f03e-f0bd-41a6-80e4-195f98cc874f

	measure 'Quantité retournée' =
			
			SUM(fct_returns[quantite_retournee])
		formatString: 0
		displayFolder: Retours
		lineageTag: beae24fe-cee5-4b9c-9240-c6e3a4907d29

	measure 'Montant remboursé HT' =
			
			SUM(fct_returns[remboursement_ht])
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: Retours
		lineageTag: 9b33a04c-834f-46fa-b395-1da70be8232e

	measure 'Commandes retournées' = ```
			
			    DISTINCTCOUNT(fct_returns[order_id])
			```
		formatString: 0
		displayFolder: Retours
		lineageTag: 3c69b174-ee50-406c-a113-3b1e7dcc6948

	measure 'Taux de retour quantité' =
			
			DIVIDE([Quantité retournée],[Quantité vendue])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: Retours
		lineageTag: b28d74ba-6891-4e6a-8e13-7b4f55f8cfcc

	measure 'Taux de remboursement CA' =
			
			DIVIDE([Montant remboursé HT],[CA HT])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: Retours
		lineageTag: f5552092-b316-4c71-932a-3aec3914358b

	measure 'CA HT N-1' =
			
			CALCULATE(
			    [CA HT]
			    , SAMEPERIODLASTYEAR(dim_date[date_jour])
			)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: CA & Revenus
		lineageTag: 37fdde77-0a68-41e9-9f40-e289859926dd

	measure 'Var CA N-1' =
			
			[CA HT] - [CA HT N-1]
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: CA & Revenus
		lineageTag: bc6e376a-28b5-4636-bf52-f8db34602434

	measure 'Var CA N-1 %' =
			
			DIVIDE([Var CA N-1], [CA HT N-1])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: CA & Revenus
		lineageTag: 9773b2fe-ff8a-4580-bb2a-21867cbf750e

	measure 'Marge HT N-1' =
			
			CALCULATE(
			    [Marge HT]
			    , SAMEPERIODLASTYEAR(dim_date[date_jour]
			    ))
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: Marges
		lineageTag: 9c1cb8e5-909f-4f7a-b2b4-1be5678196a5

	measure 'Var Marge N-1 %' =
			
			DIVIDE([Marge HT]-[Marge HT N-1], [Marge HT N-1])
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: Marges
		lineageTag: 4ef8d0b8-20ec-4183-9074-2698f177de5c

	measure 'Nb produits vendus' =
			
			DISTINCTCOUNT(fct_sales[product_id])
		formatString: 0
		displayFolder: Commandes
		lineageTag: c06fb55d-4479-4e92-81c3-6732e29bef92

	measure 'CA moyen par produit' =
			
			DIVIDE([CA HT],[Nb produits vendus])
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: CA & Revenus
		lineageTag: 9aaddfaf-cc47-4e75-bcee-47359d6fb31e

	measure 'Marge moyenne par produit' =
			
			DIVIDE([Marge HT],[Nb produits vendus])
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: Marges
		lineageTag: 4ba5deb1-457d-4329-80f9-6afc9e2bb88b

	measure 'Quantité moyenne par commande' =
			
			DIVIDE([Quantité vendue], [Nb commandes])
		formatString: 0.00
		displayFolder: Commandes
		lineageTag: c478df3b-cfe3-4ae1-ab7c-e314bd009504

	measure 'Points fidélité' =
			
			SUM(fct_loyalty_transactions[points])
		formatString: 0
		displayFolder: Fidélité
		lineageTag: 9159d4d6-4f6f-4cb6-b72d-12f44a7ee50d

	measure 'Nb transactions fidelité' =
			
			DISTINCTCOUNT(fct_loyalty_transactions[transaction_id])
		formatString: 0
		displayFolder: Fidélité
		lineageTag: 12b09dc5-42d0-4bdd-9f85-59a2fea61c29

	measure 'Points par transaction' =
			
			DIVIDE([Points fidélité],[Nb transactions fidelité])
		formatString: 0.0
		displayFolder: Fidélité
		lineageTag: 0a6f296b-7633-4672-ac34-41a34239b6ae

	measure 'Clients fidelité actif' =
			
			DISTINCTCOUNT(fct_loyalty_transactions[customer_id])
		formatString: 0
		displayFolder: Clients
		lineageTag: 2c24c877-d905-4467-a2ad-b188693ce7d2

	measure 'Taux de fidelité actifs' =
			
			DIVIDE([Clients fidelité actif],DISTINCTCOUNT(dim_customers[customer_id]))
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: Fidélité
		lineageTag: 79145a5d-2fd0-425f-a86c-54a6bb9658e8

	measure 'Stock dispo' =
			
			SUM(dim_product_variants[stock_disponible])
		formatString: 0
		displayFolder: Commandes
		lineageTag: c065a6af-34b8-4043-b045-b88f52cecfa8

	measure 'CA YTD' = TOTALYTD([CA HT], dim_date[date_jour])
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: CA & Revenus
		lineageTag: 838f29db-eb57-4e5f-8624-bcd05d6bc8e1

	measure 'Marge YTD' = TOTALYTD([Marge HT], dim_date[date_jour])
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: Marges
		lineageTag: 133ab95d-253b-4435-a4be-1cc2e68bca15

	measure 'Taux retour commande' =
			
			DIVIDE(DISTINCTCOUNT(fct_returns[order_id]),[Nb commandes])
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Retours
		lineageTag: fae7b5d9-102e-4387-8236-02e238573c10

	measure 'Points émis' =
			
			CALCULATE(
			    SUM(fct_loyalty_transactions[points])
			    , dim_loyalty_transaction_type[is_earning] = TRUE
			    )
		formatString: 0
		displayFolder: Fidélité
		lineageTag: bf64df9d-bc42-45c9-a8c2-cafd06990fef

	measure 'Points dépensés' =
			
			CALCULATE(
			    SUM(fct_loyalty_transactions[points])
			    , dim_loyalty_transaction_type[is_spending] = TRUE
			    )
		formatString: 0
		displayFolder: Fidélité
		lineageTag: 15ab9c25-dc59-4bb3-936e-f8a06fb2fff3

	measure 'Taux utilisation de points' =
			
			DIVIDE([Points dépensés],[Points émis])
		displayFolder: Fidélité
		lineageTag: 0583aea9-d6e2-43f2-8418-9392128d8900

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Score RFM moyen' =
			
			AVERAGE(dim_customers[rfm_score])
		displayFolder: Clients
		lineageTag: bc2306cc-4e11-4939-ab1d-7f3b78532504

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'LTV Moyen' =
			
			DIVIDE(
			    SUMX(dim_customers,
			        CALCULATE([CA HT])
			    ),
			    [Clients actifs]
			)
		displayFolder: Clients
		lineageTag: b3ac33f9-1706-4c94-b725-6f04b84af632

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Top produit' = ```
			
			RANKX(ALL(dim_products[product_name]),[CA HT], 
			, DESC
			, Dense
			)
			```
		formatString: 0
		displayFolder: Commandes
		lineageTag: 1627ba7f-411c-40ba-be9a-1ecdb224c572

	measure 'Flop Produit' = ```
			
			    RANKX(
			        ALL(dim_products[product_name]),
			        [CA HT],
			        ,
			        ASC,
			        DENSE
			    )
			```
		formatString: 0
		displayFolder: Commandes
		lineageTag: cee05421-a842-46b1-b453-7df94402e412

	measure 'Var CA Label N-1' =
			
			VAR v = [Var CA N-1 %]
			VAR signe =
			    IF ( v >= 0, "↗ +", "↘ " )
			RETURN
			IF (
			    ISBLANK ( v ),
			    "--",
			    signe & FORMAT ( v, "0.0%" ) & " vs N-1"
			)
		displayFolder: CA & Revenus
		lineageTag: 78bb5456-8ea4-454d-807f-8141e4b2d7a7

	measure 'Couleur Var CA' =
			
			VAR v = [Var CA N-1 %]
			RETURN
			SWITCH (
			    TRUE (),
			    ISBLANK ( v ), "#6B7280",
			    v >= 0.05, "#2E7D32",
			    v >= 0, "#7A9A3D",
			    v > -0.05, "#D97706",
			    "#B91C1C"
			)
		displayFolder: CA & Revenus
		lineageTag: b9af5a48-d0f1-4bf9-bb94-d8cb5ca655ec

	measure 'Var Margin Label N-1' =
			
			VAR v = [Var Marge N-1 %]
			VAR signe =
			    IF ( v >= 0, "↗ +", "↘ " )
			RETURN
			IF (
			    ISBLANK ( v ),
			    "--",
			    signe & FORMAT ( v, "0.0%" ) & " vs N-1"
			)
		displayFolder: Marges
		lineageTag: 1a5aa717-4d21-4ab5-8c5b-dbc0a10e7bf6

	measure 'Couleur Var Margin' =
			
			VAR v = [Var Marge N-1 %]
			RETURN
			SWITCH (
			    TRUE (),
			    ISBLANK ( v ), "#6B7280",
			    v >= 0.05, "#2E7D32",
			    v >= 0, "#7A9A3D",
			    v > -0.05, "#D97706",
			    "#B91C1C"
			)
		displayFolder: Marges
		lineageTag: 7a409f12-cbcd-4fe9-b3bf-28b784a499a5

	measure 'Nb Commandes MoM' =
			
			CALCULATE(
			    [Nb commandes]
			    , DATEADD(dim_date[date_jour], -1, MONTH)
			)
		formatString: 0
		displayFolder: Commandes
		lineageTag: b00ad5c7-2cdf-4399-84fc-3123512235a9

	measure 'Nb commandes N-1' =
			
			CALCULATE(
			    [Nb commandes]
			    , SAMEPERIODLASTYEAR(dim_date[date_jour]))
		formatString: 0
		displayFolder: Commandes
		lineageTag: c0d80559-d58b-47ce-91e8-778346c389a3

	measure 'Var Commandes MoM' =
			
			DIVIDE([Nb commandes] - [Nb Commandes MoM], [Nb Commandes MoM])
		displayFolder: Commandes
		lineageTag: 6649fb2a-99c8-4712-9061-f555edd0c47c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var Commandes N-1 %' =
			
			DIVIDE ([Nb commandes]-[Nb commandes N-1], [Nb commandes N-1])
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Commandes
		lineageTag: bf47af45-e8d8-4697-bc9d-2da21dea4532

	measure 'Var Commandes Label N-1' =
			
			VAR v = [Var Commandes N-1 %]
			VAR signe =
			    IF ( v >= 0, "↗ +", "↘ " )
			RETURN
			IF (
			    ISBLANK ( v ),
			    "--",
			    signe & FORMAT ( v, "0.0%" ) & " vs N-1"
			)
		displayFolder: Commandes
		lineageTag: 0241d3e8-7763-45e4-82df-e8751942da22

	measure 'Var Color Commandes' =
			
			VAR v = [Var Commandes N-1 %]
			RETURN
			SWITCH (
			    TRUE (),
			    ISBLANK ( v ), "#6B7280",
			    v >= 0.05, "#2E7D32",
			    v >= 0, "#7A9A3D",
			    v > -0.05, "#D97706",
			    "#B91C1C"
			)
		displayFolder: Commandes
		lineageTag: 9ae59046-ec7e-4d59-a9d3-511d12d1643c

	measure 'Nvx Clients' =
			
			CALCULATE(
			    DISTINCTCOUNT(dim_customers[customer_id])
			    , FILTER(
			        dim_customers
			        , dim_customers[date_inscription].[Date] >= MIN(dim_date[date_jour])
			        && dim_customers[date_inscription].[Date] <= MAX(dim_date[date_jour])
			    )
			    )
		formatString: 0
		displayFolder: Clients
		lineageTag: 3264a2cf-ed60-44d5-9335-e00ee27ae5c9

	measure 'Nvx Clients M-1' =
			
			CALCULATE(
			    [Nvx Clients]
			    , DATEADD(dim_date[date_jour], -1, MONTH)
			)
		formatString: 0
		displayFolder: Clients
		lineageTag: 826fbceb-fadb-4f8c-a630-33cd33168bd4

	measure 'Var Nvx Clients M-1' =
			
			VAR _current = [Nvx Clients]
			VAR _ref = [Nvx Clients M-1]
			VAR _delta = _current - _ref
			VAR _signe = IF(_delta >= 0, "↗ +", "↘ ")
			RETURN
			    IF(
			        ISBLANK(_ref),
			        "--",
			        _signe & _delta & " vs M-1"
			    )
		displayFolder: Clients
		lineageTag: ed5a9bf9-b16e-4212-bfba-65d33ee8cd8a

	measure 'Part CA Canal' =
			
			DIVIDE(
			    [CA HT]
			    , CALCULATE(
			        [CA HT]
			        , ALLSELECTED(dim_channel)
			    )
			)
		formatString: 0.0\ %;-0.0\ %;0.0\ %
		displayFolder: CA & Revenus
		lineageTag: ea15452d-bf35-4cbb-83ae-6d3bc0972743

	measure 'CA HT YTD' =
			
			CALCULATE (
			    [CA HT],
			    DATESYTD ( dim_date[date_jour] )
			)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: CA & Revenus
		lineageTag: c5354668-7822-4df1-80fa-08e1db920762

	measure 'CA HT YTD N-1' =
			
			CALCULATE (
			    [CA HT YTD],
			    SAMEPERIODLASTYEAR ( dim_date[date_jour] )
			)
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		displayFolder: CA & Revenus
		lineageTag: ae3e3cf5-8035-4be2-b099-1b983346b904

	measure 'Var CA YTD %' =
			
			DIVIDE (
			    [CA HT YTD] - [CA HT YTD N-1],
			    [CA HT YTD N-1]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: CA & Revenus
		lineageTag: 9a9afe86-aada-4925-b8e7-e43f565f98a9

	measure 'Couleur Var CA YTD' =
			
			VAR v = [Var CA YTD %]
			RETURN
			SWITCH (
			    TRUE (),
			    ISBLANK ( v ), "#6B7280",
			    v >= 0.05, "#2E7D32",
			    v >= 0, "#7A9A3D",
			    v > -0.05, "#D97706",
			    "#B91C1C"
			)
		displayFolder: CA & Revenus
		lineageTag: 62a8cb54-6ab2-43c7-81ec-183c111e08dc

	measure 'Label Comparaison YTD' =
			
			VAR CurrentMaxDate =
			    MAX ( dim_date[date_jour] )
			VAR CurrentYear =
			    YEAR ( CurrentMaxDate )
			VAR PrevYear =
			    CurrentYear - 1
			VAR EndOfSelectedYear =
			    DATE ( CurrentYear, 12, 31 )
			VAR IsFullYear =
			    CurrentMaxDate = EndOfSelectedYear
			RETURN
			IF (
			    IsFullYear,
			    "vs " & PrevYear,
			    "vs YTD " & PrevYear
			)
		displayFolder: CA & Revenus
		lineageTag: 0c204b03-c80a-4670-97a3-d051143639c4

	measure 'Marge HT YTD N-1' =
			
			CALCULATE (
			    [Marge HT],
			    SAMEPERIODLASTYEAR ( DATESYTD ( dim_date[date_jour] ) )
			)
		displayFolder: Marges
		lineageTag: c5375740-5c9c-437b-91e4-90d26b43ded7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var Marge YTD %' =
			
			DIVIDE (
			    [Marge YTD] - [Marge HT YTD N-1],
			    [Marge HT YTD N-1]
			)
		displayFolder: Marges
		lineageTag: 779c0a70-43df-4a8d-bef5-e636ff4d56b1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var CA YTD Label' =
			
			VAR v = [Var CA YTD %]
			RETURN
			IF (
			    ISBLANK ( v ),
			    "--",
			    IF (
			        v >= 0,
			        "↗ +" & FORMAT ( v, "0.0%" ),
			        "↘ " & FORMAT ( v, "0.0%" )
			    )
			)
		displayFolder: CA & Revenus
		lineageTag: 2e9fd8f3-b155-4796-ab6d-b974e0681128

	measure 'Var Marge YTD Label' =
			
			VAR v = [Var Marge YTD %]
			RETURN
			IF (
			    ISBLANK ( v ),
			    "--",
			    IF (
			        v >= 0,
			        "↗ +" & FORMAT ( v, "0.0%" ),
			        "↘ " & FORMAT ( v, "0.0%" )
			    )
			)
		displayFolder: Marges
		lineageTag: 1f4dc75b-02bd-4402-ad0f-7c83eb58e072

	measure 'Couleur Var Marge YTD' =
			
			VAR v = [Var Marge YTD %]
			RETURN
			SWITCH (
			    TRUE (),
			    ISBLANK ( v ), "#6B7280",
			    v >= 0.05, "#2E7D32",
			    v >= 0, "#7A9A3D",
			    v > -0.05, "#D97706",
			    "#B91C1C"
			)
		displayFolder: Marges
		lineageTag: e626730f-096f-41c9-a1e6-dfaddd1e9a4e

	measure 'Taux de marge YTD' = ```
			
			 DIVIDE([Marge YTD],[CA HT YTD])
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Marges
		lineageTag: 481a1db9-af29-4591-88b0-3d5151a00ac3

	measure 'Taux de marge YTD N-1' =
			
			DIVIDE([Marge HT YTD N-1], [CA HT YTD N-1])
		displayFolder: Marges
		lineageTag: 681a33f0-ffc5-4aa7-a028-a67bbba596ab

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var Taux de Marge YTD' =
			
			[Taux de marge YTD]-[Taux de marge YTD N-1]
		displayFolder: Marges
		lineageTag: 1e0d4176-043b-4e08-bef1-9ae7828006ea

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Var Taux Marge YTD Label' =
			
			VAR v = [Var Taux de Marge YTD]
			RETURN
			IF (
			    ISBLANK ( v ),
			    "--",
			    IF (
			        v >= 0,
			        "↗ +" & FORMAT ( v * 100, "0.0" ) & " pts",
			        "↘ " & FORMAT ( v * 100, "0.0" ) & " pts"
			    )
			)
		displayFolder: Marges
		lineageTag: 2c61a942-17cc-44f9-8448-5adfcf8fbf36

	measure 'Couleur Var Taux Marge YTD' =
			
			VAR v = [Var Taux de Marge YTD]
			RETURN
			SWITCH (
			    TRUE (),
			    ISBLANK ( v ), "#6B7280",
			    v >= 0.02, "#2E7D32",
			    v >= 0, "#7A9A3D",
			    v > -0.02, "#D97706",
			    "#B91C1C"
			)
		displayFolder: Marges
		lineageTag: 3f92012a-e3fe-45bb-ab89-833b6d93b644

	measure 'Nb Commandes YTD' =
			
			CALCULATE(
			    [Nb commandes]
			    , DATESYTD(dim_date[date_jour])
			)
		formatString: 0
		displayFolder: Commandes
		lineageTag: ecc4d985-d02e-44e9-ba12-ff8590f67549

	measure 'Nb Commandes YTD N-1' =
			
			CALCULATE(
			    [Nb commandes]
			    , SAMEPERIODLASTYEAR(DATESYTD(dim_date[date_jour]))
			)
		formatString: 0
		displayFolder: Commandes
		lineageTag: 579801e3-c95f-4630-ad45-89123da0edc6

	measure 'Var Commandes YTD %' =
			
			DIVIDE(
			    [Nb Commandes YTD]-[Nb Commandes YTD N-1]
			    , [Nb Commandes YTD N-1]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Commandes
		lineageTag: 06400a4e-2ac7-494e-a313-ea2496c3ce14

	measure 'Var Commmandes YTD Label' = ```
			
			VAR v = [Var Commandes YTD %]
			RETURN
			IF(
			    ISBLANK ( v ), " -- ", 
			    IF(
			        v >= 0 , 
			        "↗ +" & FORMAT ( v, "0.0%" ),
			        "↘ " & FORMAT ( v, "0.0%" )
			    )
			)
			```
		displayFolder: Commandes
		lineageTag: 8143daac-9e59-42ee-a2a5-5c9ba40f2bdb

	measure 'Couleur Var Nb commandes YTD' =
			
			VAR v = [Var Commandes YTD %]
			RETURN
			SWITCH (
			    TRUE (),
			    ISBLANK ( v ), "#6B7280",
			    v >= 0.05, "#2E7D32",
			    v >= 0, "#7A9A3D",
			    v > -0.05, "#D97706",
			    "#B91C1C"
			)
		displayFolder: Commandes
		lineageTag: d9eac4cc-5288-495f-baa7-e218f9014dfc

	measure 'Clients actifs YTD' =
			
			CALCULATE(
			    [Clients actifs]
			    , DATESYTD(dim_date[date_jour])
			)
		formatString: 0
		displayFolder: Clients
		lineageTag: 205ba254-8445-4ec4-8213-ee537071146e

	measure 'Clients Actifs YTD N-1' =
			
			CALCULATE(
			    [Clients actifs]
			    , SAMEPERIODLASTYEAR(DATESYTD(dim_date[date_jour]))
			)
		formatString: 0
		displayFolder: Clients
		lineageTag: 3ed79163-6400-481c-a8d3-fa6d800870ea

	measure 'Var Clients actifs YTD %' = ```
			DIVIDE( [Clients actifs YTD] - [Clients Actifs YTD N-1], [Clients Actifs YTD N-1] ) 
			```
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Clients
		lineageTag: 12163089-6a34-4677-8326-afa84d7f174c

	measure 'Var Clients actifs YTD Label' =
			
			VAR v = [Var Clients actifs YTD %]
			RETURN
			IF (
			    ISBLANK ( v ),
			    "--",
			    IF (
			        v >= 0,
			        "↗ +" & FORMAT ( v, "0.0%" ),
			        "↘ " & FORMAT ( v, "0.0%" )
			    )
			)
		displayFolder: Clients
		lineageTag: f52fe883-d708-4b59-b208-0f562de4ffda

	measure 'Couleur Var Clients actifs YTD' =
			
			VAR v = [Var Clients actifs YTD %]
			RETURN
			SWITCH (
			    TRUE (),
			    ISBLANK ( v ), "#6B7280",
			    v >= 0.05, "#2E7D32",
			    v >= 0, "#7A9A3D",
			    v > -0.05, "#D97706",
			    "#B91C1C"
			)
		displayFolder: Clients
		lineageTag: d4b43afd-00eb-4382-91bb-e6f33545273e

	measure 'CA moyen par commande' =
			
			DIVIDE([CA HT], [Nb commandes])
		displayFolder: CA & Revenus
		lineageTag: 0d26bfe2-0714-45ec-8874-052101f70f40

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Commandes retournées YTD' =
			
			CALCULATE(
			    DISTINCTCOUNT(fct_sales[order_id]),
			    DATESYTD(dim_date[date_jour]),
			    TREATAS(
			        VALUES(fct_returns[order_id]),
			        fct_sales[order_id]
			    )
			)
		formatString: 0
		displayFolder: Retours
		lineageTag: b6b06b5f-f279-4c25-8acc-d576377819aa

	measure 'Taux retour commande YTD' =
			
			DIVIDE(
			    [Commandes retournées YTD],
			    [Nb Commandes YTD]
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: Retours
		lineageTag: a403499e-9313-41fd-b415-8c1ab75caa71

	measure 'Part CA Canal YTD' =
			
			DIVIDE(
			    [CA HT YTD],
			    CALCULATE(
			        [CA HT YTD],
			        ALLSELECTED(dim_channel[Canal affichage])
			    )
			)
		formatString: 0.00\ %;-0.00\ %;0.00\ %
		displayFolder: CA & Revenus
		lineageTag: 7fcedcc1-a673-4e9b-ad48-e59bc18a17e7

	measure 'Taux Marge YTD Label' =
			
			"(" & FORMAT([Taux de marge YTD], "0.00%") & ")"
		displayFolder: Marges
		lineageTag: 7a3880b9-76c1-4db9-acf1-09733960a4eb

	measure 'Var nb clients actifs YTD' =
			
			[Clients actifs YTD]-[Clients Actifs YTD N-1]
		formatString: 0
		displayFolder: Clients
		lineageTag: d48fd9e3-5441-4d4e-b811-38120286da56

	measure 'Clients actifs YTD - Detail' =
			
			VAR var_nb = [Var nb clients actifs YTD]
			VAR var_pct = [Var Clients actifs YTD %]
			VAR label_comp = [Label Comparaison YTD]
			VAR arrow =
			    SWITCH(
			        TRUE(),
			        ISBLANK(var_nb), BLANK(),
			        var_nb > 0, "↗ ",
			        var_nb < 0, "↘ ",
			        "→ "
			    )
			RETURN
			IF(
			    ISBLANK(var_nb) || ISBLANK(var_pct),
			    "--",
			        " clients / "
			        & arrow
			        & FORMAT(var_pct, "+0.0%;-0.0%;0.0%")
			        & " "
			        & label_comp
			)
		displayFolder: Clients
		lineageTag: 6cd69fa6-1382-4b5b-b44e-7eec570bc4ad

	measure 'Titre Courbe CA HT vs N-1' =
			
			VAR annee_selectionnee =
			    SELECTEDVALUE(dim_date[annee])
			VAR annee_n_1 =
			    annee_selectionnee - 1
			RETURN
			IF(
			    ISBLANK(annee_selectionnee),
			    "Évolution mensuelle du CA HT",
			    "Évolution mensuelle du CA HT — "
			        & annee_selectionnee
			        & " vs "
			        & annee_n_1
			)
		displayFolder: CA & Revenus
		lineageTag: 5d7d2584-a158-4392-9bd9-d848757ee540

	partition _Mesures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Colonne 1" = _t]),
				    #"Type modifié" = Table.TransformColumnTypes(Source,{{"Colonne 1", type text}}),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Type modifié",{"Colonne 1"})
				in
				    #"Colonnes supprimées"

	annotation PBI_ResultType = Table

