table dim_date
	lineageTag: 66df2030-cceb-4f4d-a26d-9f467e345ae9
	dataCategory: Time

	column date_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 99120268-bb05-40df-b0fb-1278ed698fd4
		summarizeBy: none
		sourceColumn: date_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column date_jour
		dataType: dateTime
		isKey
		formatString: dd/mm/yyyy
		lineageTag: 122d4bf6-9401-4a13-8ca8-e5427712e8b9
		summarizeBy: none
		sourceColumn: date_jour

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column annee
		dataType: int64
		formatString: 0
		lineageTag: efa78a29-6788-45cc-b1f3-d31a3ff9859c
		summarizeBy: sum
		sourceColumn: annee

		annotation SummarizationSetBy = Automatic

	column trimestre
		dataType: int64
		formatString: 0
		lineageTag: 65c9b757-5e56-4e62-a8e2-14f2fcc55487
		summarizeBy: sum
		sourceColumn: trimestre

		annotation SummarizationSetBy = Automatic

	column trimestre_label
		dataType: string
		lineageTag: da6eb94c-a1b0-4c97-a677-86fa4bb4780c
		summarizeBy: none
		sourceColumn: trimestre_label
		sortByColumn: trimestre

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column mois
		dataType: int64
		formatString: 0
		lineageTag: e6fff74d-7cfb-4a57-8785-dcc4404ee700
		summarizeBy: sum
		sourceColumn: mois

		annotation SummarizationSetBy = Automatic

	column mois_label
		dataType: string
		lineageTag: eec275f6-615c-46e2-a510-4a0db4bb3c48
		summarizeBy: none
		sourceColumn: mois_label
		sortByColumn: mois

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column semaine
		dataType: int64
		formatString: 0
		lineageTag: 574e62bc-decf-4df3-a35e-9726b56c0bfe
		summarizeBy: sum
		sourceColumn: semaine

		annotation SummarizationSetBy = Automatic

	column jour_semaine
		dataType: int64
		formatString: 0
		lineageTag: 41a6a44f-e18c-4d4a-961b-df6ad8d8493b
		summarizeBy: sum
		sourceColumn: jour_semaine
		sortByColumn: jour_semaine_tri

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column jour_semaine_label
		dataType: string
		lineageTag: 032792b1-9899-49f2-a8ee-1ac03dc93526
		summarizeBy: none
		sourceColumn: jour_semaine_label
		sortByColumn: jour_semaine

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column annee_mois
		dataType: string
		lineageTag: fde79361-369b-460d-9e7e-ec04b2901322
		summarizeBy: none
		sourceColumn: annee_mois
		sortByColumn: annee_mois_tri

		changedProperty = DataType

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column annee_trimestre
		dataType: string
		lineageTag: b343f111-99f7-46ed-b2ab-4383edc42e99
		summarizeBy: none
		sourceColumn: annee_trimestre
		sortByColumn: annee_trimestre_tri

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e4383100-55cf-4fb5-a273-192dc2d1f753
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_current_month
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d581d846-bc18-4bcb-9c7b-5d8e0ab13b8d
		summarizeBy: none
		sourceColumn: is_current_month

		annotation SummarizationSetBy = Automatic

	column is_current_year
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a44c2dff-7280-453b-829d-b6fbf9438792
		summarizeBy: none
		sourceColumn: is_current_year

		annotation SummarizationSetBy = Automatic

	column annee_mois_tri =
			
			YEAR(dim_date[date_jour]) * 100 + MONTH(dim_date[date_jour])
		formatString: 0
		lineageTag: 10e06b55-7883-4851-af7e-400c8d44311b
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column annee_trimestre_tri =
			
			YEAR(dim_date[date_jour]) * 10 + QUARTER(dim_date[date_jour])
		formatString: 0
		lineageTag: adff04e3-7ac7-41c7-8e12-d0681a2a15fd
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column jour_semaine_tri =
			
			WEEKDAY(dim_date[date_jour], 2)
		formatString: 0
		lineageTag: 182a0f02-5490-4381-bdd5-44a6d2474cc3
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column mois_label_short
		dataType: string
		lineageTag: daa92f4e-cf9f-4215-835a-cdff0e123550
		summarizeBy: none
		sourceColumn: mois_label_short
		sortByColumn: mois

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	hierarchy 'annee Hiérarchie'
		lineageTag: cb8f327e-a2a9-4d4c-8415-33e9f27efd1d

		level annee
			lineageTag: 5a71666b-f3bd-41fb-87ab-d7a5f4cbed90
			column: annee

		level annee_trimestre
			lineageTag: f836a039-bddd-47c7-8fc4-ab5901113ce3
			column: annee_trimestre

		level annee_mois
			lineageTag: 5f84e7dd-9d89-4d43-af8e-1a4a25b49649
			column: annee_mois

		level trimestre_label
			lineageTag: 3353bdb4-cfbc-4cd3-84f6-a0c4a692353c
			column: trimestre_label

		level mois_label
			lineageTag: cad9d91f-282e-4da0-8384-c5a5d06a432c
			column: mois_label

		level mois_label_short
			lineageTag: 827efe10-937e-45bf-b9db-42ed8dce906c
			column: mois_label_short

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\manon\high-peak\exports_powerbi_csv\dim_date.csv"),[Delimiter=",", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"date_id", Int64.Type}, {"date_jour", type datetime}, {"annee", Int64.Type}, {"trimestre", Int64.Type}, {"trimestre_label", type text}, {"mois", Int64.Type}, {"mois_label", type text}, {"semaine", Int64.Type}, {"jour_semaine", Int64.Type}, {"jour_semaine_label", type text}, {"annee_mois", type date}, {"annee_trimestre", type text}, {"is_weekend", type logical}, {"is_current_month", type logical}, {"is_current_year", type logical}}),
				    #"Duplication de la colonne" = Table.DuplicateColumn(#"Type modifié", "mois_label", "mois_label - Copier"),
				    #"Colonnes renommées" = Table.RenameColumns(#"Duplication de la colonne",{{"mois_label - Copier", "mois_label_short"}}),
				    #"Valeur remplacée" = Table.ReplaceValue(#"Colonnes renommées","January","Jan",Replacer.ReplaceText,{"mois_label_short"}),
				    #"Valeur remplacée1" = Table.ReplaceValue(#"Valeur remplacée","February","Feb",Replacer.ReplaceText,{"mois_label_short"}),
				    #"Valeur remplacée2" = Table.ReplaceValue(#"Valeur remplacée1","March","Mar",Replacer.ReplaceText,{"mois_label_short"}),
				    #"Valeur remplacée3" = Table.ReplaceValue(#"Valeur remplacée2","April","Apr",Replacer.ReplaceText,{"mois_label_short"}),
				    #"Valeur remplacée4" = Table.ReplaceValue(#"Valeur remplacée3","June","Jun",Replacer.ReplaceText,{"mois_label_short"}),
				    #"Valeur remplacée5" = Table.ReplaceValue(#"Valeur remplacée4","July","Jul",Replacer.ReplaceText,{"mois_label_short"}),
				    #"Valeur remplacée6" = Table.ReplaceValue(#"Valeur remplacée5","August","Aug",Replacer.ReplaceText,{"mois_label_short"}),
				    #"Valeur remplacée7" = Table.ReplaceValue(#"Valeur remplacée6","September","Sep",Replacer.ReplaceText,{"mois_label_short"}),
				    #"Valeur remplacée8" = Table.ReplaceValue(#"Valeur remplacée7","October","Oct",Replacer.ReplaceText,{"mois_label_short"}),
				    #"Valeur remplacée9" = Table.ReplaceValue(#"Valeur remplacée8","November","Nov",Replacer.ReplaceText,{"mois_label_short"}),
				    #"Valeur remplacée10" = Table.ReplaceValue(#"Valeur remplacée9","December","Dec",Replacer.ReplaceText,{"mois_label_short"})
				in
				    #"Valeur remplacée10"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

