table dim_date
	lineageTag: 66df2030-cceb-4f4d-a26d-9f467e345ae9
	dataCategory: Time

	column date_id
		dataType: int64
		formatString: 0
		lineageTag: 99120268-bb05-40df-b0fb-1278ed698fd4
		summarizeBy: none
		sourceColumn: date_id

		annotation SummarizationSetBy = Automatic

	column date_jour
		dataType: dateTime
		isKey
		formatString: General Date
		lineageTag: 122d4bf6-9401-4a13-8ca8-e5427712e8b9
		summarizeBy: none
		sourceColumn: date_jour

		annotation SummarizationSetBy = Automatic

	column annee
		dataType: int64
		formatString: 0
		lineageTag: efa78a29-6788-45cc-b1f3-d31a3ff9859c
		summarizeBy: sum
		sourceColumn: annee

		annotation SummarizationSetBy = Automatic

	column trimestre
		dataType: int64
		formatString: 0
		lineageTag: 65c9b757-5e56-4e62-a8e2-14f2fcc55487
		summarizeBy: sum
		sourceColumn: trimestre

		annotation SummarizationSetBy = Automatic

	column trimestre_label
		dataType: string
		lineageTag: da6eb94c-a1b0-4c97-a677-86fa4bb4780c
		summarizeBy: none
		sourceColumn: trimestre_label

		annotation SummarizationSetBy = Automatic

	column mois
		dataType: int64
		formatString: 0
		lineageTag: e6fff74d-7cfb-4a57-8785-dcc4404ee700
		summarizeBy: sum
		sourceColumn: mois

		annotation SummarizationSetBy = Automatic

	column mois_label
		dataType: string
		lineageTag: eec275f6-615c-46e2-a510-4a0db4bb3c48
		summarizeBy: none
		sourceColumn: mois_label

		annotation SummarizationSetBy = Automatic

	column semaine
		dataType: int64
		formatString: 0
		lineageTag: 574e62bc-decf-4df3-a35e-9726b56c0bfe
		summarizeBy: sum
		sourceColumn: semaine

		annotation SummarizationSetBy = Automatic

	column jour_semaine
		dataType: int64
		formatString: 0
		lineageTag: 41a6a44f-e18c-4d4a-961b-df6ad8d8493b
		summarizeBy: sum
		sourceColumn: jour_semaine

		annotation SummarizationSetBy = Automatic

	column jour_semaine_label
		dataType: string
		lineageTag: 032792b1-9899-49f2-a8ee-1ac03dc93526
		summarizeBy: none
		sourceColumn: jour_semaine_label

		annotation SummarizationSetBy = Automatic

	column annee_mois
		dataType: dateTime
		formatString: Long Date
		lineageTag: fde79361-369b-460d-9e7e-ec04b2901322
		summarizeBy: none
		sourceColumn: annee_mois

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column annee_trimestre
		dataType: string
		lineageTag: b343f111-99f7-46ed-b2ab-4383edc42e99
		summarizeBy: none
		sourceColumn: annee_trimestre

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e4383100-55cf-4fb5-a273-192dc2d1f753
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_current_month
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d581d846-bc18-4bcb-9c7b-5d8e0ab13b8d
		summarizeBy: none
		sourceColumn: is_current_month

		annotation SummarizationSetBy = Automatic

	column is_current_year
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a44c2dff-7280-453b-829d-b6fbf9438792
		summarizeBy: none
		sourceColumn: is_current_year

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\manon\high-peak\exports_powerbi_csv\dim_date.csv"),[Delimiter=",", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"date_id", Int64.Type}, {"date_jour", type datetime}, {"annee", Int64.Type}, {"trimestre", Int64.Type}, {"trimestre_label", type text}, {"mois", Int64.Type}, {"mois_label", type text}, {"semaine", Int64.Type}, {"jour_semaine", Int64.Type}, {"jour_semaine_label", type text}, {"annee_mois", type date}, {"annee_trimestre", type text}, {"is_weekend", type logical}, {"is_current_month", type logical}, {"is_current_year", type logical}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

