table dim_products
	lineageTag: 8fdc1498-5ae2-4829-a911-3b286540077e

	column product_id
		dataType: string
		lineageTag: 591e2f4a-792a-46b6-9ee5-3b94ec534c59
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 70484c35-8178-4da2-bbe8-59eb6a94e0fa
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column category_id
		dataType: string
		lineageTag: 1d76199d-7d34-46dc-9fa8-c1addece0f8a
		summarizeBy: none
		sourceColumn: category_id

		annotation SummarizationSetBy = Automatic

	column categorie
		dataType: string
		lineageTag: d362e389-d55b-4ad8-a45c-42789d3445a8
		summarizeBy: none
		sourceColumn: categorie

		annotation SummarizationSetBy = Automatic

	column sous_categorie
		dataType: string
		lineageTag: 1da84f0c-1274-4eeb-963b-c45395f7a224
		summarizeBy: none
		sourceColumn: sous_categorie

		annotation SummarizationSetBy = Automatic

	column saison
		dataType: string
		lineageTag: e2c53524-a318-488c-8524-1db7f4307f50
		summarizeBy: none
		sourceColumn: saison

		annotation SummarizationSetBy = Automatic

	column supplier_id
		dataType: string
		lineageTag: 473aa7ab-9de0-43c0-a95d-98538ef2fd64
		summarizeBy: none
		sourceColumn: supplier_id

		annotation SummarizationSetBy = Automatic

	column prix_vente_ht
		dataType: string
		lineageTag: 2cf8c805-918d-4567-8e70-93b5f6087ade
		summarizeBy: none
		sourceColumn: prix_vente_ht

		annotation SummarizationSetBy = Automatic

	column prix_achat_ht
		dataType: string
		lineageTag: 062d73b9-0680-47a6-aa6b-241b45a19160
		summarizeBy: none
		sourceColumn: prix_achat_ht

		annotation SummarizationSetBy = Automatic

	column marge_unitaire_ht
		dataType: string
		lineageTag: c45864a9-c5dd-4ee4-9a3a-ceb36a7d3b1c
		summarizeBy: none
		sourceColumn: marge_unitaire_ht

		annotation SummarizationSetBy = Automatic

	column taux_marge_pct
		dataType: string
		lineageTag: b4457393-881e-409a-a5e4-28cca30247b6
		summarizeBy: none
		sourceColumn: taux_marge_pct

		annotation SummarizationSetBy = Automatic

	column has_negative_margin
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 827a062d-484a-4221-85f8-1141df0792b4
		summarizeBy: none
		sourceColumn: has_negative_margin

		annotation SummarizationSetBy = Automatic

	partition dim_products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\manon\high-peak\exports_powerbi_csv\dim_products.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"product_id", type text}, {"product_name", type text}, {"category_id", type text}, {"categorie", type text}, {"sous_categorie", type text}, {"saison", type text}, {"supplier_id", type text}, {"prix_vente_ht", type text}, {"prix_achat_ht", type text}, {"marge_unitaire_ht", type text}, {"taux_marge_pct", type text}, {"has_negative_margin", type logical}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

