table fct_sales
	lineageTag: 34871be4-9c24-4718-a8f1-86788c280eb8

	column order_item_id
		dataType: string
		isHidden
		lineageTag: e33450da-a45b-4cee-962e-d4de89e6a36a
		summarizeBy: none
		sourceColumn: order_item_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column date_id
		dataType: string
		isHidden
		lineageTag: 0394f576-41f3-4534-a484-8adb4c5e3365
		summarizeBy: none
		sourceColumn: date_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: string
		isHidden
		lineageTag: 081ca9ce-cc19-4e06-aa33-6c2e3ebff7d5
		summarizeBy: none
		sourceColumn: customer_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_id
		dataType: string
		isHidden
		lineageTag: 3379bd5f-8e48-484f-805e-5d5122dd0924
		summarizeBy: none
		sourceColumn: product_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column store_id
		dataType: string
		isHidden
		lineageTag: b11c330d-c46a-4a62-89d9-2fbf20a4391f
		summarizeBy: none
		sourceColumn: store_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column promotion_id
		dataType: string
		isHidden
		lineageTag: 2e4c93ee-3052-4211-b779-d33f08d4d768
		summarizeBy: none
		sourceColumn: promotion_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column channel_id
		dataType: string
		isHidden
		lineageTag: 4aaf8c1f-3172-46c5-8c6a-a7d649b54c82
		summarizeBy: none
		sourceColumn: channel_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_status_id
		dataType: string
		isHidden
		lineageTag: ca59797f-9c9e-4772-bc6d-d94c679f4702
		summarizeBy: none
		sourceColumn: order_status_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quantite
		dataType: string
		lineageTag: 39525aa9-2b8f-47a1-b150-34e992a85506
		summarizeBy: none
		sourceColumn: quantite

		annotation SummarizationSetBy = Automatic

	column prix_unitaire_ht
		dataType: double
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 47317454-9659-4479-b6ae-091fa43f49e7
		summarizeBy: sum
		sourceColumn: prix_unitaire_ht

		annotation SummarizationSetBy = Automatic

	column remise_pct
		dataType: double
		formatString: 0.00
		lineageTag: d6b33d16-01e1-4e02-b044-0686528ac115
		summarizeBy: sum
		sourceColumn: remise_pct

		annotation SummarizationSetBy = Automatic

	column ca_ligne_ht
		dataType: double
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: fd6bbf68-214d-4552-99e5-e51f58c15300
		summarizeBy: sum
		sourceColumn: ca_ligne_ht

		annotation SummarizationSetBy = Automatic

	column ca_ligne_ttc
		dataType: double
		formatString: #,0.00\ "€";-#,0.00\ "€";#,0.00\ "€"
		lineageTag: 3428bc05-1ae1-4c83-8f81-ca1dff8837e7
		summarizeBy: sum
		sourceColumn: ca_ligne_ttc

		annotation SummarizationSetBy = Automatic

	column marge_ligne_ht
		dataType: double
		formatString: 0.00
		lineageTag: d729fdbd-bf28-4d89-b42d-e4e44b2951d5
		summarizeBy: sum
		sourceColumn: marge_ligne_ht

		annotation SummarizationSetBy = Automatic

	column taux_marge_ligne_pct
		dataType: double
		lineageTag: ac6cd20b-feb2-4b92-b518-603c2a0b2ca6
		summarizeBy: sum
		sourceColumn: taux_marge_ligne_pct

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column variant_id
		dataType: string
		isHidden
		lineageTag: 7cc550a3-499c-4c53-984f-4143ba745313
		summarizeBy: none
		sourceColumn: variant_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_id
		dataType: string
		isHidden
		lineageTag: 3ac707be-62d8-4d2e-8ebd-d1f26d0d3293
		summarizeBy: none
		sourceColumn: order_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition fct_sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\manon\high-peak\exports_powerbi_csv\fct_sales.csv"),[Delimiter=",", Columns=17, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Valeur remplacée" = Table.ReplaceValue(#"En-têtes promus",".",",",Replacer.ReplaceText,{"prix_unitaire_ht", "remise_pct", "ca_ligne_ht", "ca_ligne_ttc", "marge_ligne_ht", "taux_marge_ligne_pct"}),
				    #"Type modifié" = Table.TransformColumnTypes(#"Valeur remplacée",{{"prix_unitaire_ht", type number}}),
				    #"Valeur remplacée1" = Table.ReplaceValue(#"Type modifié",".",",",Replacer.ReplaceText,{"remise_pct"}),
				    #"Type modifié1" = Table.TransformColumnTypes(#"Valeur remplacée1",{{"remise_pct", type number}, {"ca_ligne_ht", type number}, {"ca_ligne_ttc", type number}, {"marge_ligne_ht", type number}, {"taux_marge_ligne_pct", type number}})
				in
				    #"Type modifié1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

